Added and enabled more Indian Languages
matecat/MateCat pull request #1817
Opened 2020-10-15 09:55 UTC by vinayaksharmagh

I have added language codes for some additional Indian languages (Sanskrit, Bihari, Kashmiri and Pali) and have enabled them.

2020-10-15 10:01 UTC, Ostico commented
Hi @vinayaksharmagh , thank you for your contribution, we will check if the codes match with our internal systems and in the case we will accept your PR.

2020-10-15 15:41 UTC, lorenzosecchi commented
**Bihari**: Codes are the same as ISO standards
The language is absent on all our systems (Matecat, MyMemory and Core)

**Kashmiri**: Codes are the same as ISO standards
The language is absent on Matecat e Core
The language is present on MyMemory (codes are the same)

**Pali**: Codes are the same as ISO standards
The language is absent on all our systems (Matecat, MyMemory and Core)

**Sanskrit**: Codes are different from ISO standards
should be:
{
            "localized":[{
                "en":"Sanskrit"
            }],
            "isocode":"sa",
            "enabled":true,
            "rtl":false,
            "rfc3066code":"sa-IN"
        }
The language is absent on Matecat e Core
The language is present on MyMemory (codes are different, the correct ones are the ones in MyMemory as per ISO standards)

2020-10-15 15:43 UTC, lorenzosecchi reviewed
Bihari: Codes are the same as ISO standards
The language is absent on all our systems (Matecat, MyMemory and Core)

Kashmiri: Codes are the same as ISO standards
The language is absent on Matecat e Core
The language is present on MyMemory (codes are the same)

Pali: Codes are the same as ISO standards
The language is absent on all our systems (Matecat, MyMemory and Core)

Sanskrit: Codes are different from ISO standards
should be:
{
"localized":[{
"en":"Sanskrit"
}],
"isocode":"sa",
"enabled":true,
"rtl":false,
"rfc3066code":"sa-IN"
}
The language is absent on Matecat e Core
The language is present on MyMemory (codes are different, the correct ones are the ones in MyMemory as per ISO standards)

2020-10-15 15:50 UTC, Ostico requested changes

2020-10-15 15:50 UTC, Ostico commented on lib/Utils/Langs/supported_langs.json
> +            "rfc3066code":"sn-IN"
Hi @vinayaksharmagh can you adjust this code to `sa-IN` and the isocode value to `sa`

2020-10-15 16:00 UTC, vinayaksharmagh commented on lib/Utils/Langs/supported_langs.json
> +            "rfc3066code":"sn-IN"
Yes, I have made the desired adjustments.
Please check.

https://github.com/matecat/MateCat/pull/1817/commits/f24037aa9df24dbdedef105552065f8558018fba

2020-10-15 16:17 UTC, lorenzosecchi approved these changes
Codes are allo OK now ;)

2020-10-16 05:36 UTC, vinayaksharmagh commented
@Ostico If everything is fine, can you please accept the merge now?

2020-10-16 13:42 UTC, Ostico commented on lib/Utils/Langs/supported_langs.json
> +            "rfc3066code":"sn-IN"
Perfect thank You.

2020-10-16 13:43 UTC, Ostico approved these changes

2020-10-16 13:45 UTC, Ostico commented
Hi @vinayaksharmagh we will accept for sure your PR, but we have to adjust our internal systems accordingly before the merge.

2020-10-19 15:22 UTC, merged