Update nodejs
matecat/MateCat pull request #1985
Opened 2021-04-26 10:21 UTC by riccio82

2021-04-26 10:28 UTC, cloud-walker requested changes

2021-04-26 10:28 UTC, cloud-walker commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
@Ostico , @riccio82  dato che abbiamo lockato la versione nel package.json, per grunt, direi forse di lockarla anche negli altri due package.json?

2021-04-26 10:28 UTC, cloud-walker commented on nodejs/package-lock.json
> -      "name": "matecat-sse",
@riccio82 vedo un sacco di pacchetti rimossi, non è che forse erano installati in qualche modo strano? La situazione mi puzza un pò

2021-04-26 10:28 UTC, cloud-walker commented on nodejs/package-lock.json
> +  "lockfileVersion": 1,
questa versione è cambiata, e sembra che sia legata ad npm 7, quindi qualcuno ha generato questo lock precedentemente, usando npm 7 (abbiamo npm 6 da quanto ho capito)

https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion

2021-04-26 11:41 UTC, riccio82 commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
Quello di node e quello nella root?

2021-04-26 12:23 UTC, cloud-walker commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
si

2021-04-26 12:24 UTC, cloud-walker commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
lo farei per consistenza, io personalmente non uso l'opzione `engines` su AMP, però dato che il processo di deployment dei vari environments di MateCat è messo com'è messo, lockarla mi sembra la cosa migliore

2021-04-26 12:26 UTC, cloud-walker requested changes

2021-04-26 12:26 UTC, cloud-walker commented on nodejs/server.js
> -var SseChannel = require( 'sse-channel' );
@riccio82 la cartella nodejs non è ignorata dal prettierignore? Forse non hai configurato l'editor per rispettare il prettierignore?

In ogni caso arriverei ad applicare prettier anche qui effettivamente 🤔 solo non vorrei farlo in questa PR che non c'entra nulla!

2021-04-26 12:53 UTC, riccio82 commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
Allora, pensandoci bene, una volta aggiornate tutte le macchine si potrebbe anche togliere, prima aveva senso perché Matecat supportava solo una versione vecchia di node, se passiamo alla latest forse si può omettere.

2021-04-26 12:56 UTC, riccio82 commented on nodejs/package-lock.json
> +  "lockfileVersion": 1,
Un bel mistero, ora npm è alla 6 quindi ok così.

2021-04-26 13:00 UTC, riccio82 commented on nodejs/server.js
> -var SseChannel = require( 'sse-channel' );
In realtà nel prettierignore c'è ma credo che PhpStorm se ne sia altamente sbattuto.

2021-04-26 13:01 UTC, riccio82 commented on nodejs/package-lock.json
> -      "name": "matecat-sse",
Abbiamo aggiornato lodash e sse-channel. Non saprei..

2021-04-26 13:02 UTC, cloud-walker commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
Beh, se prima o poi troviamo un modo per rendere consistente la versione di node cross-environment, a me va bene pure di ometterla.

E un discorso di rendere l'aggiornamento di versione esplicito e facile da cambiare in futuro, ma effettivamente, mettendo engines non risolviamo il problema, tanto se un domani toccherà mette la 16 ad esempio, sarà di nuovo un lago di sangue.

Magari però documenterei la versione attuale da qualche parte, in modo che non sono le macchine di produzione le uniche detentrici della verità.

Tipo sul readme?

2021-04-26 13:07 UTC, riccio82 commented on support_scripts/grunt/package.json
> +    "node": "14.16.1"
Si, ok

2021-04-26 13:24 UTC, riccio82 commented on nodejs/server.js
> -var SseChannel = require( 'sse-channel' );
Revertate le modifiche di prettier.

2021-04-26 13:26 UTC, cloud-walker commented on nodejs/package-lock.json
> -      "name": "matecat-sse",
Boh, c'è modo di testare questa parte?

2021-04-26 13:27 UTC, riccio82 commented on nodejs/package-lock.json
> -      "name": "matecat-sse",
Faremo il deploy su beta.

2021-04-26 17:19 UTC, Ostico commented on nodejs/package-lock.json
> -      "name": "matecat-sse",
queste sono le dipendenze necessarie:
``` 
    "lodash": "^4.17.19",
    "node-ini": "^1.0.0",
    "sse-channel": "^4.0.0",
    "stompit": "^0.21.0",
    "winston": "^1.0.0"
```

2021-04-26 17:27 UTC, Ostico submitted a review, later dismissed

2021-04-26 17:32 UTC, Ostico submitted a review, later dismissed

2021-04-26 17:39 UTC, cloud-walker submitted a review, later dismissed

2021-04-27 11:23 UTC, Ostico submitted a review, later dismissed

2021-04-28 11:06 UTC, Ostico approved these changes
Updated code and dependencies, refactory and partially re-written

2021-04-28 11:25 UTC, Ostico approved these changes

2021-04-28 11:26 UTC, Ostico approved these changes

2021-04-28 11:26 UTC, Ostico commented on nodejs/package.json
> +    "node": ">=10.0.0"
@riccio82 please note

2021-04-28 16:56 UTC, Ostico approved these changes

2021-04-28 17:04 UTC, Ostico commented
Please note, travis build failed because the travis file in the develop branch wants node 9, this branch requires node 14.

```
Now using node v9.11.2 (npm v5.6.0)
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for matecat-tasks@1.0.0: wanted: {"node":"14.16.1"} (current: {"node":"9.11.2","npm":"5.6.0"})
```

Force accept.

2021-04-28 17:06 UTC, Ostico submitted a review, later dismissed

2021-04-28 17:31 UTC, cloud-walker commented
> Please note, travis build failed because the travis file in the develop branch wants node 9, this branch requires node 14.
> 
> ```
> Now using node v9.11.2 (npm v5.6.0)
> npm ERR! code ENOTSUP
> npm ERR! notsup Unsupported engine for matecat-tasks@1.0.0: wanted: {"node":"14.16.1"} (current: {"node":"9.11.2","npm":"5.6.0"})
> ```
> 
> Force accept.

Yes, we currently merged a suboptimal travis config, waiting for this PR to be merged

2021-04-29 15:35 UTC, cloud-walker submitted a review, later dismissed

2021-05-03 08:52 UTC, cloud-walker commented
@riccio82 , @Ostico any update on this?

2021-05-03 09:00 UTC, riccio82 commented
Today we will speak about this and schedule the version change on servers.

2021-05-03 14:54 UTC, Ostico approved these changes

2021-05-05 09:22 UTC, Ostico approved these changes

2021-05-05 09:24 UTC, merged