Context-group: hide if structure not respect specifications
matecat/MateCat pull request #2023
Opened 2021-05-17 08:53 UTC by riccio82

2021-05-17 09:09 UTC, cloud-walker requested changes

2021-05-17 09:09 UTC, cloud-walker commented on public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
> +          })
@riccio82 qua puoi eliminare la mutation di `contextElems` usando un map, tipo:

```javascript
const contextElems = contextGroup.contexts.map((context) => (
  <div
    className="context-item"
    key={contextGroup.id + context.attr['context-type']}
  >
    <span className="context-item-name">{context.content}</span>
  </div>
))
```

2021-05-17 09:22 UTC, riccio82 commented on public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
> +          })
Done

2021-05-20 08:25 UTC, Ostico approved these changes

2021-05-20 08:34 UTC, cloud-walker approved these changes

2021-05-20 09:00 UTC, merged