Refactoring/manage
matecat/MateCat pull request #2039
Opened 2021-05-26 10:33 UTC by riccio82

2021-05-26 17:34 UTC, cloud-walker requested changes

2021-05-26 17:34 UTC, cloud-walker commented on public/js/cat_source/es6/actions/ManageActions.js
> +  ) {
eviterei di aggiungere ennemila parametri in una funzione, meglio fare un singolo parametro stile "props" (è anche più leggibile quando chiami la funzione:


```javascript
  renderProjects: function ({
    projects,
    team,
    teams,
    hideSpinner,
    filtering = false,
  }) {
```

ovviamente poi ti devi ricordare di aggiornare i punti in cui chiami questa funzione :D

2021-05-26 17:34 UTC, cloud-walker commented on public/js/cat_source/es6/actions/ManageActions.js
>      })
Qui puoi ridurre il codice così:

```javascript
AppDispatcher.dispatch({
  actionType: ManageConstants.RENDER_PROJECTS,
  projects,
  team,
  teams,
  hideSpinner,
  filtering,
})
```

2021-05-26 17:34 UTC, cloud-walker commented on public/js/cat_source/es6/components.js
> +  require('./components/notificationsComponent/NotificationBox').default
Qui io ho cominciato a rimuovere i `require` e ad usare gli `import`

2021-05-26 17:34 UTC, cloud-walker commented on public/js/cat_source/es6/components/header/manage/FilterProjects.js
>  class FilterProjects extends React.Component {
e mettemocelo uno spazio tra gli import e la classe 😅

2021-05-26 17:34 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/Header.js
> +import ReactDOM from 'react-dom'
e mettemocelo uno spazio tra gli import e la classe 😅

2021-05-26 17:34 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/Header.js
> +}
non credo ti serva un class component per usare le API dei portals 🤔

2021-05-27 08:50 UTC, riccio82 commented on public/js/cat_source/es6/components.js
> +  require('./components/notificationsComponent/NotificationBox').default
Si, è una modifica solo di formattazione in realtà, non l'ho aggiutno.

2021-05-27 09:00 UTC, riccio82 commented on public/js/cat_source/es6/components/projects/Header.js
> +}
Mi ci trovo meglio quando con Flux, forse è solo questione di abitudine.

2021-05-27 09:04 UTC, riccio82 commented on public/js/cat_source/es6/actions/ManageActions.js
> +  ) {
Dici che cambia qualcosa? Non lo trovo molto più comodo...

2021-05-27 09:08 UTC, riccio82 commented
Ora il branch è funzionante ma devo sistemare i test.

2021-05-27 09:21 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/Header.js
> +}
Ma qui non usi Flux, o sbaglio?

2021-05-27 09:33 UTC, riccio82 commented on public/js/cat_source/es6/components/projects/Header.js
> +}
Si hai ragione, qui no.

2021-05-27 09:45 UTC, cloud-walker commented on public/js/cat_source/es6/actions/ManageActions.js
> +  ) {
addirittura puoi anche non passare i `null` nel secondo caso, mentre nel primo sei costretto perché fanno parte dei parametri e non dell'oggetto, quindi sarebbe in realtà: 

```javascript
showModalComponent({
  component: Greeting,
  title: 'Awesome title',
  onCloseCallback: () => console.log('ciao'),
})
```

2021-05-27 09:47 UTC, riccio82 commented on public/js/cat_source/es6/actions/ManageActions.js
> +  ) {
Ok, mi hai convinto 👍🏽

2021-06-09 09:32 UTC, cloud-walker requested changes

2021-06-09 09:58 UTC, cloud-walker approved these changes

2021-06-09 14:00 UTC, cloud-walker commented on Gruntfile.js
> +          basePath + 'cat_source/es6/components/projects/*.js',
così stai includendo anche il test `Dashboard.test.js`, non riusciamo ad importare solo l'entry point?

2021-06-22 08:37 UTC, cloud-walker approved these changes

2021-06-22 08:38 UTC, merged