Created test for JobContainer components
matecat/MateCat pull request #2089
Opened 2021-07-07 08:46 UTC by piedicianni

2021-07-07 10:41 UTC, cloud-walker requested changes

2021-07-07 10:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  fireEvent.click(aTag)
quando lavori con gli eventi preferisci `@testing-library/user-event` che è un pacchetto fatto apposta per simulare le interazioni come le farebbe l'utente vero

2021-07-07 10:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  fireEvent.click(aTag)
Quindi in questo caso `userEvent.click(aTag)`

2021-07-07 10:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  })
Non mi è chiaro cosa vuoi fare con questo `.addEventListener`

2021-07-07 10:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(onClick).toHaveBeenCalled()
Non mi è chiaro cosa vuoi fare qui (forse è legato a quello che cercavate di dirmi in call stamattina 😅 )

2021-07-07 10:42 UTC, cloud-walker commented
@piedicianni review del progress della PR mandata, come detto su Slack parte della review te la farà eslint in automatico appena farai rebase da develop!

2021-07-07 10:52 UTC, piedicianni commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(onClick).toHaveBeenCalled()
@cloud-walker qua semplicemente sto assegnando un listener sull'onclick (ha lo stopPropagation di modo che non venga invocata la funzione originale del componente) serve solo per controllare che effettivamente quel pulsante risulti cliccabile.
Ma forse c'è un modo migliore per farlo...

2021-07-07 10:54 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(onClick).toHaveBeenCalled()
penso che ti basti usare il matcher di `jest-dom` `.toBeEnabled()` (sempre se è un bottone vero quello..)

2021-07-09 07:51 UTC, piedicianni commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(onClick).toHaveBeenCalled()
@cloud-walker ottimo grazie Luca, ho cambiato quel comportamento utilizzando jest-dom, tutto ok! :)

2021-07-09 09:41 UTC, cloud-walker requested changes

2021-07-09 09:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(idElement).toHaveTextContent(`ID: ${job.get('id')}`)
Non so bene il senso di quel `title` su un div, dal punto di vista semantico e dell'accessiblità, personalmente semplificherei questo pezzo così:

```javascript
  expect(screen.getByTitle(`ID: ${job.get('id')}`)).toBeVisible()
```

2021-07-09 09:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(sourceElement).toHaveClass('source-box')
Io eliminerei questa riga, l'attributo `class` dell'HTML è un dettaglio implementativo che rende il test solo più fragile al cambiamento, e non testa veramente che questo elemento abbia l'aspetto che vogliamo lato stile.

2021-07-09 09:41 UTC, cloud-walker commented on public/js/cat_source/es6/components/projects/JobContainer.test.js
> +  expect(targetElement).toHaveClass('target-box')
Io eliminerei questa riga, l'attributo `class` dell'HTML è un dettaglio implementativo che rende il test solo più fragile al cambiamento, e non testa veramente che questo elemento abbia l'aspetto che vogliamo lato stile.

2021-07-09 10:24 UTC, cloud-walker approved these changes

2021-07-09 11:06 UTC, merged