Gruntfile: move manage concat to browserify
matecat/MateCat pull request #2095
Opened 2021-07-08 15:28 UTC by riccio82

@cloud-walker eliminato in file di build 👍🏽

2021-07-08 16:44 UTC, cloud-walker requested changes

2021-07-08 16:44 UTC, cloud-walker commented on Gruntfile.js
> +          basePath + 'cat_source/es6/ajax_utils/*.js',
bannerei gli asterischi

2021-07-09 12:25 UTC, riccio82 commented on Gruntfile.js
> +          basePath + 'cat_source/es6/ajax_utils/*.js',
Il problema è capire quali sono i file che servono...

2021-07-09 12:32 UTC, riccio82 commented on Gruntfile.js
> +          basePath + 'cat_source/es6/ajax_utils/*.js',
Ci provo.

2021-07-09 13:35 UTC, cloud-walker commented on Gruntfile.js
> +          basePath + 'cat_source/es6/ajax_utils/*.js',
come ci siamo detti a voce, possiamo anche semplicemente includerli tutti senza asterisco per ora, senza controllare quali sono quelli necessari

2021-07-09 14:05 UTC, cloud-walker approved these changes

2021-07-09 14:17 UTC, merged