Develop segment tags for tos
matecat/MateCat pull request #2140
Opened 2021-07-30 11:05 UTC by mauretto78

2021-08-09 12:01 UTC, Ostico approved these changes

2021-09-15 12:47 UTC, Ostico requested changes

2021-09-15 12:47 UTC, Ostico commented on lib/Model/LQA/EntryDao.php
> +                matecat.qa_entries e
@mauretto78  This schema name is wrong, schema addressing must be removed.

2021-10-04 11:09 UTC, mauretto78 commented on lib/Model/LQA/EntryDao.php
> +                matecat.qa_entries e
@Ostico fixed.
(the brach `mauretto78:develop-segment-tags-for-tos` is actually merged with develop)

2021-10-04 13:14 UTC, Ostico approved these changes

2021-10-04 14:21 UTC, merged