Refactoring ajax request mixed inside files
matecat/MateCat pull request #2207
Opened 2021-09-27 15:54 UTC by piedicianni

2021-09-28 08:35 UTC, cloud-walker requested changes

2021-09-28 08:35 UTC, cloud-walker commented on public/js/cat_source/es6/api/enableOrDisableTagLexica/enableOrDisableTagLexica.js
> +export const enableOrDisableTagLexica = async (
propongo `toggleTagLexica`?

2021-09-28 08:35 UTC, cloud-walker commented on public/js/cat_source/es6/api/enableOrDisableTagProjectionJob/enableOrDisableTagProjectionJob.js
> +export const enableOrDisableTagProjectionJob = async (
propongo `toggleTagProjectionJob`

2021-09-28 08:35 UTC, cloud-walker commented on public/js/cat_source/es6/api/getLexiqaWarnings/getLexiqaWarnings.js
> +  password = config.password,
Eviterei di creare una lista infinita di parametri di configurazione, puoi fare un oggetto "options" che li contiene tutti

2021-09-28 08:35 UTC, cloud-walker commented on public/js/cat_source/es6/api/getLexiqaWarnings/getLexiqaWarnings.js
> +  password = config.password,
Se siete d'accordo, propagherei lo stesso concetto anche alle altre chiamate della PR

2021-09-28 09:35 UTC, piedicianni commented on public/js/cat_source/es6/api/getLexiqaWarnings/getLexiqaWarnings.js
> +  password = config.password,
@cloud-walker Ok, appena ritorno su MateCat effettuo queste modifiche, grazie!

2021-10-13 13:41 UTC, cloud-walker commented on public/js/cat_source/es6/utils/lxq.main.js
> +      // lexiqaIgnoreError({errorid});
Commento

2021-10-13 13:42 UTC, cloud-walker commented on public/js/cat_source/review_extended/review_extended.ui_extension.js
> +import {deleteSegmentIssue as deleteSegmentIssueApi} from '../es6/api/deleteSegmentIssue'
perche' rinomini la funzione qui?

2021-10-13 13:50 UTC, piedicianni commented on public/js/cat_source/review_extended/review_extended.ui_extension.js
> +import {deleteSegmentIssue as deleteSegmentIssueApi} from '../es6/api/deleteSegmentIssue'
Gli ho preferito cambiare il nome perchè in quel file c'è già una funzione che si chiama`deleteSegmentIssues` (con la "s" finale).

2021-10-20 07:51 UTC, merged