Develop api blacklist
matecat/MateCat pull request #2245
Opened 2021-11-18 14:50 UTC by mauretto78

**Blacklist API endpoints**

**[POST] /api/v3/glossary/blacklist/upload**

Upload a blacklist.

Params:

- `jid` (string)
- `password` (string)
- `file` (file)

Response sample:

```json
{
    "success": true,
    "id": "23"
}
```

The returned `id` can be used for fetching and deleting purposes. 

The API throws an error if Blacklist already exists, only ONE blacklist file is allowed for a job.

**[DELETE] /api/v3/glossary/blacklist/delete/[:id_file]**

Deletes a persisted blacklist.

Response sample:

```json
{
    "success": true,
    "id": "23"
}
```

**[GET] /api/v3/glossary/blacklist/get/[:id_file]**

Provides the full details of a persisted blacklist. 

Response sample:

```json
{
    "id": "5",
    "id_job": "148",
    "password": "54dda8e0437b",
    "file_path": "glossary/148/54dda8e0437b/blacklist.txt",
    "file_name": "blacklist.txt",
    "target": "it-IT",
    "uid": "0",
    "content": [
        "cavolo",
        "palla",
        "pollo"
    ]
}
```

2021-11-24 15:54 UTC, Ostico requested changes

2021-11-24 15:54 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist.php
> +            'from_upload'         => BlacklistUtils::checkIfExists($chunk->id, $chunk->password),
Too slow, for each set translation it will block the user and slow down the system.

2021-11-24 15:55 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist.php
> +            'from_upload'         => BlacklistUtils::checkIfExists($chunk->id, $chunk->password),
It is better to place this info somewhere and use a cache layer on it.

2021-11-25 13:32 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist.php
> +            'from_upload'         => BlacklistUtils::checkIfExists($chunk->id, $chunk->password),
@Ostico I introduced a Redis cache layer. Is it enough for you?

- https://github.com/matecat/MateCat/pull/2245/commits/da13a1de14672b6517adcd4c71b74056b8cd18de
- https://github.com/matecat/MateCat/pull/2245/commits/5ad1f1e36dbf1a436a46c0900780a50e21fcb460

2021-12-23 11:37 UTC, Ostico requested changes

2021-12-23 11:37 UTC, Ostico commented on lib/Controller/API/V3/BlacklistController.php
> +            $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
Why not `RedisHandler::getConnection()` class but a new Predis instance??

2021-12-23 11:37 UTC, Ostico commented on lib/Model/FilesStorage/AbstractFilesStorage.php
> +        if ( $isFsOnS3 ) {
You tested both configurations? ( S3/Fs )

2021-12-23 11:37 UTC, Ostico commented on lib/Model/Glossary/Blacklist/BlacklistDao.php
> +    public function save( BlacklistModel $blacklistStruct){
`save( BlacklistModel $blacklistStruct )` , this is not a Model is a struct as the variable says, can you uniform class name?

2021-12-23 11:37 UTC, Ostico commented on lib/Model/Glossary/Blacklist/BlacklistDao.php
> +            'id_job' => $blacklistStruct->chunk->id,
If we ude the properties with the same names of the database fields:
`'id_job' => $blacklistStruct->chunk->id_job,`

we do not need to map into an array because the structs has `ArrayAccess` interface and anyway they have the method `getArrayCopy()`

2021-12-23 11:37 UTC, Ostico commented on lib/Model/Projects/ProjectModel.php
> +        $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
Same here, why not `RedisHandler` ?

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist.php
> +        $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
Same here, why not `RedisHandler::getConnection()` ?

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist/AbstractBlacklist.php
> +        $this->redis = new \Predis\Client( \INIT::$REDIS_SERVERS );
Do not hardcode the redis client, set it as dependency, better code reuse and tests. 

Inject `RedisHandler->getConnection()`

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist/AbstractBlacklist.php
> +        $redis   = new \Predis\Client( \INIT::$REDIS_SERVERS );
See previous comment

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist/AbstractBlacklist.php
> +        $redis           = new \Predis\Client( \INIT::$REDIS_SERVERS );
See previous comment

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist/BlacklistFromZip.php
> +        // TODO: Implement deleteOriginalFile() method.
I think that we will never use this method since the original package must be immutable.

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist/Utils/BlacklistUtils.php
> +        $job = \Jobs_JobDao::getByIdAndPassword($model->id_job, $model->password);
Set a cache on jobdao requests, we need only id and password here and they do not changes, btw even if they changes, a new redis value is set.

2021-12-23 11:37 UTC, Ostico commented on lib/Plugins/Features/QaCheckBlacklist/Worker/BlacklistWorker.php
> +        $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
same, `RedisHandler::getConnection()`

2021-12-23 11:37 UTC, Ostico commented on migrations/20211130110000_create_table_blacklist_files.php
> +            KEY `uid` (`uid`) USING BTREE,
Can you please explain the field and the key `uid`?
We need them?

2021-12-23 15:33 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist.php
> +        $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
Done

2021-12-23 15:33 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist/AbstractBlacklist.php
> +        $this->redis = new \Predis\Client( \INIT::$REDIS_SERVERS );
Done

2021-12-23 15:33 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist/AbstractBlacklist.php
> +        $redis   = new \Predis\Client( \INIT::$REDIS_SERVERS );
Done

2021-12-23 15:33 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist/AbstractBlacklist.php
> +        $redis           = new \Predis\Client( \INIT::$REDIS_SERVERS );
Done

2021-12-23 15:33 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist/BlacklistFromZip.php
> +        // TODO: Implement deleteOriginalFile() method.
Removed

2021-12-23 15:33 UTC, mauretto78 commented on lib/Plugins/Features/QaCheckBlacklist/Utils/BlacklistUtils.php
> +        $job = \Jobs_JobDao::getByIdAndPassword($model->id_job, $model->password);
Set a 1 hour cache

2021-12-23 15:34 UTC, mauretto78 commented on lib/Model/Projects/ProjectModel.php
> +        $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
Done

2021-12-23 15:35 UTC, mauretto78 commented on lib/Model/Glossary/Blacklist/BlacklistDao.php
> +            'id_job' => $blacklistStruct->chunk->id,
I introduced the `toPlainArray` method on the struct which uses `toArray()` method

2021-12-23 15:35 UTC, mauretto78 commented on lib/Model/Glossary/Blacklist/BlacklistDao.php
> +    public function save( BlacklistModel $blacklistStruct){
Renamed to `BlacklistStruct`

2021-12-23 15:35 UTC, mauretto78 commented on lib/Model/FilesStorage/AbstractFilesStorage.php
> +        if ( $isFsOnS3 ) {
Yes I tested both

2021-12-23 15:35 UTC, mauretto78 commented on lib/Controller/API/V3/BlacklistController.php
> +            $blacklistUtils = new BlacklistUtils(new \Predis\Client( \INIT::$REDIS_SERVERS ));
Done

2021-12-23 15:44 UTC, mauretto78 commented on migrations/20211130110000_create_table_blacklist_files.php
> +            KEY `uid` (`uid`) USING BTREE,
`uid` could be useful don't you think? In any case I can easily remove it

2021-12-27 12:07 UTC, closed without merging