MMT code update
matecat/MateCat pull request #2440
Opened 2022-05-24 09:28 UTC by riccio82

2022-12-30 15:14 UTC, Ostico requested changes

2022-12-30 15:14 UTC, Ostico commented on lib/Controller/AbstractControllers/viewController.php
> +    /**
@mauretto78 why this piece of code here? should be in the plugin

2022-12-30 15:18 UTC, Ostico requested changes

2022-12-30 15:18 UTC, Ostico commented on lib/Model/Jobs/JobStruct.php
> +    public function isArchiveable() {
@mauretto78 this should be removed?

2023-01-02 14:58 UTC, Ostico submitted a review, later dismissed

2023-01-25 14:54 UTC, mauretto78 approved these changes

2023-01-25 15:06 UTC, Ostico approved these changes

2023-01-25 15:09 UTC, merged