Added size restriction to the endpoint /v3/word-count/raw
matecat/MateCat pull request #2644
Opened 2023-02-01 11:36 UTC by mauretto78

2023-02-02 13:58 UTC, Ostico requested changes

2023-02-02 13:58 UTC, Ostico commented on lib/Controller/API/V3/CountWordController.php
> +                'remaining_characters' => $size_restriction->getCharactersRemaining(),
@mauretto78 remaining characters could not be used in this API. It would be all the time

2023-02-02 14:34 UTC, Ostico requested changes

2023-02-02 14:34 UTC, Ostico commented on lib/Controller/API/V3/CountWordController.php
> +                'remaining_characters' => $size_restriction->getCharactersRemaining(),
Forget about my comment, please change the behaviour as we discussed. :)

2023-02-23 13:51 UTC, riccio82 approved these changes

2023-02-23 13:53 UTC, Ostico submitted a review, later dismissed

2023-02-23 13:58 UTC, Ostico approved these changes

2023-02-23 14:01 UTC, merged