Segment bucketing refactor
matecat/MateCat pull request #3227
Opened 2024-03-20 10:35 UTC by mauretto78

2024-03-21 10:18 UTC, Ostico requested changes

2024-03-21 10:18 UTC, Ostico commented on lib/Utils/Analysis/Workers/TMAnalysisWorker.php
> +            if($ind_fast > $ind){
@mauretto78 this conditional branch return the same value `$tm_match_fuzzy_band`. I suspect it's a typo.

2024-03-21 10:55 UTC, mauretto78 commented on lib/Utils/Analysis/Workers/TMAnalysisWorker.php
> +            if($ind_fast > $ind){
@Ostico fixed, thanks :)

2024-03-25 13:58 UTC, piedicianni approved these changes

2024-03-25 14:09 UTC, Ostico approved these changes

2024-03-25 14:12 UTC, merged