Social login refactoring
matecat/MateCat pull request #3254
Opened 2024-04-05 10:15 UTC by mauretto78

2024-04-05 14:30 UTC, Ostico requested changes
Please also ensure that PhpDoc is added to all new methods, and if possible, to the existing ones that lack it when encountered.

2024-04-05 14:30 UTC, Ostico commented on .htaccess
>  RewriteRule ^(oauth)/(response)[/]?$ index.php?action=oauthResponseHandler [L,QSA]
Would be better if we remove those routes and pass them to Klein or KleinViewController

2024-04-05 14:30 UTC, Ostico commented on lib/Utils/ConnectedServices/Google/GoogleClientFactory.php
> +        $client->setApplicationName( \INIT::$OAUTH_CLIENT_APP_NAME );
Please Add `use namespace` instead of `\` root namespace in the class initializations.

2024-04-05 14:30 UTC, Ostico commented on lib/Controller/AbstractControllers/BaseKleinViewController.php
>          $this->view->gdriveAuthURL = \ConnectedServices\GDrive::generateGDriveAuthUrl();
Please Add `use namespace` instead of `\` root namespace in the class initializations.

2024-04-05 14:30 UTC, Ostico commented on lib/Controller/AbstractControllers/viewController.php
>          $this->template->gdriveAuthURL        = \ConnectedServices\GDrive::generateGDriveAuthUrl();
Please Add `use namespace` instead of `\` root namespace in the class initializations.

2024-04-05 14:30 UTC, Ostico commented on lib/Controller/oauthResponseHandlerController.php
> +            $provider = $this->provider ?? OauthClient::GOOGLE_PROVIDER;
This is not needed since google provider is the default.

2024-04-05 14:30 UTC, Ostico commented on lib/Utils/ConnectedServices/GDrive/GDriveClientFactory.php
> +        return GoogleClientFactory::create(\INIT::$HTTPHOST . "/gdrive/oauth/response");
Please Add `use namespace` instead of `\` root namespace in the class initializations.

2024-04-05 14:30 UTC, Ostico commented on lib/Model/ConnectedServices/GDriveUserAuthorizationModel.php
> +     * @throws \Exception
Please Add `use namespace` instead of `\` root namespace in the class initializations.

2024-04-05 16:09 UTC, mauretto78 commented on lib/Controller/AbstractControllers/BaseKleinViewController.php
> +        $oauth_client = OauthClient::getInstance(OauthClient::GOOGLE_PROVIDER)->getClient();
Done

2024-04-05 16:09 UTC, mauretto78 commented on lib/Controller/AbstractControllers/BaseKleinViewController.php
>          $this->view->gdriveAuthURL = \ConnectedServices\GDrive::generateGDriveAuthUrl();
Done

2024-04-05 16:09 UTC, mauretto78 commented on lib/Controller/oauthResponseHandlerController.php
> +            $provider = $this->provider ?? OauthClient::GOOGLE_PROVIDER;
Done

2024-04-05 16:09 UTC, mauretto78 commented on lib/Utils/ConnectedServices/GDrive/GDriveClientFactory.php
> +        return GoogleClientFactory::create(\INIT::$HTTPHOST . "/gdrive/oauth/response");
Done

2024-04-05 16:11 UTC, mauretto78 commented on lib/Utils/ConnectedServices/GDrive/GDriveClientFactory.php
> +        return GoogleClientFactory::create(\INIT::$HTTPHOST . "/gdrive/oauth/response");
Done, I am trying to remove root namespaces everywhere

2024-04-08 14:50 UTC, mauretto78 commented on .htaccess
>  RewriteRule ^(oauth)/(response)[/]?$ index.php?action=oauthResponseHandler [L,QSA]
Done

2024-04-17 13:31 UTC, closed without merging